stages:
 - build
 - build_dev

build:
 stage: build
 image: docker:latest
 tags:
   - docker
 variables:
    DOCKER_DRIVER: overlay2
 services:
    - docker:dind
 before_script:
   - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
 script:
   - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME" .
   - docker push "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME"

trigger_dev_build:
  image: alpine
  stage: build_dev
  tags:
   - docker
  before_script:
    - apk add --no-cache curl
  script:
    - "curl -X POST -F token=2069a6e5ea93b995d11f69febbd261 -F ref=dev https://gitlab.com/api/v4/projects/6578509/trigger/pipeline"