stages:
 - build
 - build_dev

build:
 image: docker:latest
 stage: build
 tags:
   - docker
 before_script:
   - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
 script:
   - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME" .
   - docker push "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME"

trigger_dev_build:
  image: alpine
  stage: build_dev
  tags:
   - docker
  before_script:
    - apk add --no-cache curl
  script:
    - "curl -X POST -F token=99a2c51317b36d34be08376818609c -F ref=dev https://git.mighty-code.com/api/v4/projects/2/trigger/pipeline"