build:
 stage: build
 tags:
   - docker
 script:
   - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
   - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME" .
   - docker push "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME"

trigger_dev_build:
  image: alpine
  stage: build
  script:
    - "curl -X POST -F token=8402daa56fbd49b2e1cdb59f16f9a2 -F ref=dev https://gitlab.com/api/v4/projects/5785772/trigger/pipeline"